min_events:
  sop1: 8000
  sop2: 5000
  sop3: 20000

detector_limits:
  voltage: 0.01
  gain: 0.01

edge_event_threshold: 0.999

time_limits:
  spike_limit: 1000
  gap_limit: 0.05
  non_mono_limit: 100
  rate_thresh: 50
  min_size: 500
